// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCvwyy170xot5ksIbKiCHDvN_AtHyH75M',
    appId: '1:524591266755:web:9035d88063f262ff819b76',
    messagingSenderId: '524591266755',
    projectId: 'reserve-go-3d460',
    authDomain: 'reserve-go-3d460.firebaseapp.com',
    storageBucket: 'reserve-go-3d460.firebasestorage.app',
    measurementId: 'G-LSTQC7B0NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfDtxUbeaXEihzp6wUv7pA3zaYoDcKvxc',
    appId: '1:524591266755:android:fe1a89286282edcf819b76',
    messagingSenderId: '524591266755',
    projectId: 'reserve-go-3d460',
    storageBucket: 'reserve-go-3d460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfZDkjy8pn9KUrzPHoCe7AIgFT7y99kMQ',
    appId: '1:524591266755:ios:6743f1bd50cbd60b819b76',
    messagingSenderId: '524591266755',
    projectId: 'reserve-go-3d460',
    storageBucket: 'reserve-go-3d460.firebasestorage.app',
    iosBundleId: 'com.reserve.go1',
  );
}
